### ISSUE TITLE
Login "TypeError: failed to fetch"

### ISSUE THREAD

**Issue by NOCTLJRNE** [EOSIO/eosio-card-game-repo#2]
Hi, I was trying the tutorial and encountered the following errors: (on Windows PC):

output from running quick_start.sh 
https://1drv.ms/u/s!Aob-VU6_enselOMSbp0tIzzYsq9GtA

login error:
https://1drv.ms/u/s!Aob-VU6_enselOMTeXsCpidZ6VsJFw

I couldn't log in with the credential given: Account: player1 & Private Key: 5KFyaxQW8L6uXFB6wSgC44EsAbzC7ideyhhQ68tiYfdKQp69xKo

Please help, thank you in advance for your support.

**Comment by ChristianDunst** [comment]
Hi NOCTLJRNE,

I looked at your trace and the problem is that you are building on a Windows system. Unfortunately Windows is currently not supported by the EOSIO environment.

I have attached a screenshot of our supported environments. You can use a virtual machine, cloud solution or dual boot to solve your problem.

Good luck
<img width="518" alt="screen shot 2018-12-12 at 12 14 34 pm" src="https://user-images.githubusercontent.com/14068265/49846735-ae761300-fe07-11e8-9c6c-4193d032e5bc.png">
